### PR TITLE
#15 Reviewed new French labels

### PR DESCRIPTION
**Pull request by syllant**

### CODE REVIEW

**Comment by melitele** [comment]
Thank you so much for correcting the translation.

'Spread’ or range (extent, span) is the distance from the route limiting the search along the route. It's displayed under Search options (button in the right top corner) in the Sleep/Eat/Find drawers. Does any of the following words have that meaning: 'envergure', 'portée', 'gamme', 'périmètre'?

**Comment by syllant** [comment]
OK, I understand now for "Spread". I would recommend "Périmètre".

**Comment by melitele** [comment]
Thank you. Will do.

**Comment by melitele** [comment]
Sorry, I missed your other question.

'Label Roads' is an option under Map View options (a globe-like icon in the middle of map toolbar) that causes major roads to be marked (labeled with names) when the map is set to satellite. When the 'Label Roads' option is off there are no names displayed over roads in the satellite view.

**Comment by melitele** [comment]
Hi Sylvain,

please ignore my comment about Label Roads if you received it. I’ve misread the diff and attributed your check about Peages to it.

Regards,
Natalia

**Comment by melitele** [comment]
Please ignore my comment about 'Label Roads' - I misread the diff. Sorry about that.

**Pull request merged**
